### ISSUE TITLE
/usr/bin/ld: cannot find -ltensorflow-lite

### ISSUE THREAD

**Issue by mcwoojcik** [Qengineering/TensorFlow_Lite_Pose_RPi_64-bits#2]
Hello - I did everything follow your instructions for install TensorFlowLite on RPi4 and when I'm trying to build Pose project with code block I'm obtaining this error:

/usr/bin/ld cannot find -ltensorflow-lite

I was looking for a solution but I wasn't able to fix it. Did you maybe have a similar problem or do you have some ideas?

Shared libraries vs Static libraries...

I tried it under virtual Raspbian using VirtualBox

**Comment by Qengineering** [comment]
I'm sorry to hear about your problem.
The installation of TensorFlow generates the tensorflow-lite.a library in this location.
![image](https://user-images.githubusercontent.com/44409029/84412032-ed5c7300-ac0e-11ea-9556-89295f06b89f.png)
Somehow Code::Blocks couldn't find this file. Please check the the _Search directories_ tab in the menu _Project build options_. There are three tabs: Compiler, Linker and Resource compiler.
In the Linker tab there you can find the locations where Code::Blocks looks for the library. Please check these locations. If your location differs from the ones mentions, add your location to the list.

**Comment by mcwoojcik** [comment]
Yes, I did it before because I had to add the correct path to libtensorflow-lite.a library so in linker for sure I have proper path. That's why I'm surprised... 
I will try today with real RPi - maybe is the problem Raspbian OS under Virtualbox

**Comment by mcwoojcik** [comment]
It works on real RPi properly... So it is a million possible reasons why it wasn't working under virtual RPi. Thanks for your response :)

**Comment by Qengineering** [comment]
Glad to hear!
