### ISSUE TITLE
cannot find VerifyField<int8_t>

### ISSUE THREAD

**Issue by tattain404** [Qengineering/TensorFlow_Lite_Pose_RPi_64-bits#3]
Hello - I did everything follow the instructions from https://qengineering.eu/install-tensorflow-2-lite-on-raspberry-64-os.html
for installing TensorFlow Lite on RPi4B with Bullseye 64-bits OS

Dependencies was fully installed and the C++ installation was successful, after exchanging the old version of flatbuffers and successful compilation,  i got two libraries and two folders with header files.
![2022-02-08-030833_1920x1080_scrot](https://user-images.githubusercontent.com/33203044/152925852-f58209e3-e3fe-4db6-bc52-cb9b1c9f2a22.png)

but when i run TestTensorFlow_Lite.cpb with Code::Blocks, comes out the following errors. That VerifyField<int8_t> is missing.

![2022-02-08-030032_1920x1080_scrot](https://user-images.githubusercontent.com/33203044/152925844-9bababe6-292c-415d-b31a-4acf8e4964b8.png)
![2022-02-08-030319_1920x1080_scrot](https://user-images.githubusercontent.com/33203044/152925850-481b959b-7c10-44d4-a45f-b36edf5fa475.png)

could you please tell me, how can i solve this problem?

**Comment by Qengineering** [comment]
Which TensorFlow Lite version did you use?
I can try to reproduce the issue at the office here.

**Comment by tattain404** [comment]
I tried tensorflow lite 2.6.0 and 2.4.0 both, comes out with the same result

> Which TensorFlow Lite version did you use? I can try to reproduce the issue at the office here.

**Comment by tattain404** [comment]
> Which TensorFlow Lite version did you use? I can try to reproduce the issue at the office here.

Hi, when you use the tflite, do you meet the same problem? I try to rebuild the system, but the problem remains.

**Comment by Qengineering** [comment]
It took some time to solve the problem. It seems the issue is related to the latest flatbuffers release. If you use the previous version every compiles well.
`git clone -b v2.0.0 --depth=1 --recursive https://github.com/google/flatbuffers.git`

**Comment by tattain404** [comment]
> It took some time to solve the problem. It seems the issue is related to the latest flatbuffers release. If you use the previous version every compiles well. `git clone -b v2.0.0 --depth=1 --recursive https://github.com/google/flatbuffers.git`

Thx a lot, it works!
